### ISSUE TITLE
Download mp4 files?

### ISSUE THREAD

**Issue by kiwifilm** [douglas-watson/podcasts_export_app#5]
Hi, ever since Apple Podcasts moved from the iTunes environment when all podcast files were saved in an accessabale directory which could be accessed via finder. But now the downloads are all stored in a segmented and user unreadable format. Podurama is the only app I have found so far where the files are stored in their native format, but unfortunately I am experiencing some delays in their feeds ampared to Apple Podcasts.

But finding your app suddenly excited me as it gives direc access to the Podacasts download folder contents.

My excitement quickly faded when I discovered this only exports mp3 files. My interest is to capture mp4 video files which several online shows are using more frequently.

What are the odds that you can enable mp4 files from Apple Podcasts app? This would be a lifesaver for me, as already shows I want to grab are already available in Podcasts app but have not yet appeared in Podurama which is the only app I found where I can see these original downloads in finder.

I'll definitely buy you next beer of 3 if you can make this happen.

- Justin

**Comment by douglas-watson** [comment]
Hi Justin,

It was actually a quite easy change, here's an updated version: https://github.com/douglas-watson/podcasts_export_app/releases/tag/v1.2.0

I only tested with one podcast, the first I could find with videos: https://podcasts.apple.com/ch/podcast/apple-events-video/id275834665. Let me know if it works on your end.

**Comment by kiwifilm** [comment]
Actually, I mentioned .mp4 video because when I found the downloads folder for Podurama they had downloaded and saved as .mp4. however when I look at the xml file I see they are listed as .m4v and these files are still not downloading. Maybe you need to ad in more extensions. Actually, couldn't you use a wildcard to accept all extensions? Apart from the fact that there are quite a large number of extensions used in av file distribution, some people distribute pdf files using rss, not just audio visual media as in podcasts.
