### ISSUE TITLE
Feature Request: Podcast Length

### ISSUE THREAD

**Issue by CzechJiri** [douglas-watson/podcasts_export_app#6]
I typically push the downloaded/exported podcasts to shokz MP3 player as file (for my 45min swimming), i have a lot of podcasts and cherry pick based on length (skip really short and really long one)

it would be great to have one more column to show length of the podcast specifically adding `MP3.info.length` would be very useful

**Comment by douglas-watson** [comment]
Thanks for the suggestion! I've added the column, you should be able to install the new version: https://github.com/douglas-watson/podcasts_export_app/releases/tag/v1.2.2

**Comment by CzechJiri** [comment]
absolutely amazing !!!!
